utils: revert back to OCL configuration and test out nproc usage

diff --git a/.github/workflows/coverity.yml b/.github/workflows/coverity.yml
--- a/.github/workflows/coverity.yml
+++ b/.github/workflows/coverity.yml
@@ -40,34 +40,30 @@ jobs:
       - uses: actions/checkout@v4
       - name: Download Linux 64 Coverity Tool
         run: |
-          curl https://scan.coverity.com/download/cxx/linux64 --output ${GITHUB_WORKSPACE}/cov-linux64-tool.tar.gz \
-            --data "token=${{secrets.COVERITY_TOKEN}}&project=${{env.COVERITY_PROJECT}}"
-          mkdir cov-linux64-tool
-          tar -xzf cov-linux64-tool.tar.gz --strip 1 -C cov-linux64-tool
-      - name: Download Intel compiler
-        run: |
-          wget --progress=dot:giga https://registrationcenter-download.intel.com/akdlm/IRC_NAS/cd63be99-88b0-4981-bea1-2034fe17f5cf/intel-dpcpp-cpp-compiler-2025.1.0.573_offline.sh
-          sudo bash intel-dpcpp-cpp-compiler-2025.1.0.573_offline.sh -s -a -s --action install --eula accept
-      - name: Prepare and run Coverity build
-        run: |
-          source /opt/intel/oneapi/setvars.sh
-          export CC=icx
-          export CXX=icpx
-          export PATH="${PWD}/cov-linux64-tool/bin:${PATH}"
-          cov-configure --template --compiler icx --comptype intel_icx:linux
-          mkdir -p build && cd build
-          cmake .. -DDNNL_CPU_RUNTIME=SYCL -DDNNL_GPU_RUNTIME=SYCL
-          cov-build --dir cov-int cmake --build . --parallel $(nproc)
-      #    ctest
-      - name: Archive Coverity build results
-        run: |
-          cd build
-          tar -czvf cov-int.tgz cov-int
-      - name: Upload Coverity build results
-        uses: actions/upload-artifact@v4
-        with:
-          name: cov-int
-          path: ./build/cov-int.tgz
+          echo "nproc: "
+          $(nproc)
+      #     curl --fail https://scan.coverity.com/download/cxx/linux64 --output ${GITHUB_WORKSPACE}/cov-linux64-tool.tar.gz \
+      #       --data "token=${{secrets.COVERITY_TOKEN}}&project=${{env.COVERITY_PROJECT}}" || { echo "Download failed"; exit 1; }
+      #     mkdir cov-linux64-tool
+      #     tar -xzf cov-linux64-tool.tar.gz --strip 1 -C cov-linux64-tool
+      # - name: Prepare and run Coverity build
+      #   run: |
+      #     export CC=gcc
+      #     export CXX=g++
+      #     export PATH="${PWD}/cov-linux64-tool/bin:${PATH}"
+      #     mkdir -p build && cd build
+      #     cmake ..
+      #     cov-build --dir cov-int cmake --build . --parallel $(nproc)
+      # #    ctest
+      # - name: Archive Coverity build results
+      #   run: |
+      #     cd build
+      #     tar -czvf cov-int.tgz cov-int
+      # - name: Upload Coverity build results
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: cov-int
+      #     path: ./build/cov-int.tgz
       # - name: Submit Coverity results for analysis
       #   run: |
       #     cd build
